name             'Task2b'
maintainer       'Dmytro'
maintainer_email 'dfad1ripe@gmail.com'
license          'All rights reserved'
description      'Installs/Configures Task2b'
long_description 'Installs/Configures Task2b'
version          '0.1.1'
issues_url       'http://bash.im/'
source_url       'https://github.com/dfad1ripe/df_devops_task2'
